sudo: false
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
language: python
install:
    - pip install -r requirements.txt
    - pip install coveralls
python:
#    - "2.7"
#    - "3.4"
#    - "3.5"
    - "3.6"
addons:
  apt:
    packages:
    - libfftw3-dev
script:
    - nosetests -v --with-coverage --cover-package=chebpy
after_success:
    - coveralls
